refs #21 ヘッダ背景色変更
code-for-hamamatsu/vaccinecert-faq pull request #29
Opened 2021-12-14 13:44 UTC by hmatsu47

フッタ背景色を変えるには Copyright 部分の書き換えが必要になりそうなので、Copyright 部分の表記が確定してから直したほうが良さそうです。

## 👏 解決する issue / Resolved Issues
- #21
- 一旦ヘッダのみの対応なので close はしません。

## 📝 関連する issue / Related Issues
- #10

## ⛏ 変更内容 / Details of Changes

- ヘッダ背景色をテーマカラーに
- ヘッダ文字色を白に（バナーと同じに）

## 📸 スクリーンショット / Screenshots

![image](https://user-images.githubusercontent.com/35142774/146009623-99c96178-5836-4ee2-985d-dd9935fa8678.png)
 - テーマカラーと同じ色に変わります。

2021-12-14 15:19 UTC, hmatsu47 commented
ちなみに、フッタを現状の Copyright 表記のまま構造を変えずに対応すると、

- モバイルではそれなりの感じになりますが（でもちょっと厚く感じる？）
<img width="464" alt="スクリーンショット 2021-12-15 0 12 20" src="https://user-images.githubusercontent.com/35142774/146025922-f642c2a0-a39a-41bb-8ab3-ced543ee01cf.png">

- PC ではヘッダと違って横幅が 960px（左右にマージンあり）になってしまうので微妙です。
<img width="1035" alt="スクリーンショット 2021-12-15 0 12 42" src="https://user-images.githubusercontent.com/35142774/146026233-94a2b2df-28db-4ab2-a7a0-51f449982f3c.png">

2021-12-15 00:53 UTC, hmatsu47 commented
よく考えたらスマホも横画面にすると左右にマージンが入る可能性がありますね。

個人的には先にヘッダだけ対応してフッタは12/20バージョンでは現状のままにしておくのが良いと思いますが、いかがでしょうか？

2021-12-15 12:41 UTC, ww2or3ww requested changes
@hmatsu47 確認しました。
ここではフッタのことは触れず、ヘッダだけに集中しましょうか。
1点コメントを加えましたのでご確認をお願いします〜

2021-12-15 12:41 UTC, ww2or3ww commented on layouts/_default/baseof.html
> +    <header class="banner shadow-bottom sticky-top bg-primary">
差分はここの1行だけ、ということですよね。
```
<header class="shadow-bottom sticky-top bg-white">
↓
<header class="banner shadow-bottom sticky-top bg-primary">
```
カラーコード指定のほうがいいかな？と思いましたがどうでしょうか。
yutoさんが対応している https://github.com/code-for-hamamatsu/vaccinecert-faq/pull/28#issuecomment-992996005 こちらと同じにするイメージです。

2021-12-15 13:09 UTC, hmatsu47 commented on layouts/_default/baseof.html
> +    <header class="banner shadow-bottom sticky-top bg-primary">
実質的な差分はそこだけです。
yuto さんの`config.toml`（`primary_color`）変更の反映によって、`bg-primary` で指定している背景色が赤（`#B10020`）になります（今後、仮に`config.toml`で色設定を変えた場合にもその変更が反映されます）。

先頭の `banner` 指定で、文字（リンク）の文字色がトップ（Home）のヘッダと同じ白（`white_color` : `#FFFFFF`）になります。
これをしないと文字（変更前は`text_color` : `#636363`）がヘッダの背景色に埋もれてしまって読みづらくなります。

2021-12-15 13:36 UTC, ww2or3ww approved these changes

2021-12-15 13:36 UTC, ww2or3ww commented on layouts/_default/baseof.html
> +    <header class="banner shadow-bottom sticky-top bg-primary">
@hmatsu47 なるほど、既にそうなっているということですね👍
ありがとうございました！

2021-12-15 13:45 UTC, hmatsu47 commented
で、実はちょっとした問題点も見つけていまして。
画面幅を狭くしたときにヘッダの右側がハンバーガーメニューに変わると、ハンバーガーメニューのアイコンの色が暗いので見にくくなるという・・・。

![image](https://user-images.githubusercontent.com/35142774/146197386-87cf3581-584e-46ec-9dfa-feb5c71be1f1.png)

ただ、これは（さっきの時点で一旦触るのをやめておいた）`style.css`を`assets/css/`の下に持ってきて、

```css:
.navbar-dark .navbar-toggler-icon {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255, 255, 255, 1)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
}
```

の`.navbar-dark`を`.navbar-light`に変えてやると見やすくなることがわかりました。

![image](https://user-images.githubusercontent.com/35142774/146197513-a482df51-24d9-4109-92aa-1a00ca5ee74d.png)

2021-12-15 13:51 UTC, hmatsu47 commented
こちら↑もついでに直しました。
`style.css`の 282 行目です。

2021-12-15 14:19 UTC, hmatsu47 commented
あーごめんなさい！
修正するファイルを間違えていて、ハンバーガーメニューのほうはやっぱり`assets/css/style.css`への上書きではダメでした。
（昨日試したときにダメだったので今日うまく行ったのは何故？となっていたのですが）。

Approved 後にすみませんが、`style.css`のほうは一旦取り消します。

2021-12-15 14:25 UTC, euledge commented on layouts/_default/baseof.html
> +    <header class="banner shadow-bottom sticky-top bg-primary">
「ヘッダに集中」　同意です

2021-12-15 14:40 UTC, ww2or3ww commented
@hmatsu47 色々とご確認をありがとうございます！
それではこのチケットでは、あくまで背景色だけということにしましょう。
ハンバーガーメニューやフッターのレイアウトは別途Issueということで！

2021-12-15 14:41 UTC, ww2or3ww commented on layouts/_default/baseof.html
> +    <header class="banner shadow-bottom sticky-top bg-primary">
@euledge 問題なさそうであれば、Approveお願いします〜🤲

2021-12-15 16:21 UTC, euledge approved these changes
LGTM

2021-12-15 16:22 UTC, merged