Feature/93 add social share button
code-for-hamamatsu/vaccinecert-faq pull request #97
Opened 2021-12-30 14:22 UTC by euledge

## 👏 解決する issue / Resolved Issues
- close #93
- close #0

## 📝 関連する issue / Related Issues
- #0
- #0

## ⛏ 変更内容 / Details of Changes

- カテゴリページの回答の下にソーシャルシェアボタンを配置

## 📸 スクリーンショット / Screenshots

### PC 
![image](https://user-images.githubusercontent.com/1209580/147760067-f398f37b-473d-4590-8e31-b99ce9972ef4.png)

### モバイル(開発ツールでの見た目)
![image](https://user-images.githubusercontent.com/1209580/147760135-712e8b55-924d-4d05-ad96-2d85368695de.png)

2021-12-30 14:26 UTC, euledge commented
プレビューはこちら
https://feature-93-add-social-share-button.dchofm2ginq7s.amplifyapp.com/

2021-12-30 15:33 UTC, hmatsu47 approved these changes
掲載されているスクリーンショットの通り Facebook が OGP 無効状態みたいですが、これは認証を掛けているからでしょうかね。
ほか、一通り触ってみた感じでは大丈夫そうですね！

2021-12-30 22:09 UTC, ww2or3ww requested changes
確認しました〜
やっぱり実際に動かして見れるといいですね！

・検索結果ページへの対応が漏れているようです。
・アコーディオンの＋/−マークが消えてしまっている？ようです。
![Screenshot_20211231-070522](https://user-images.githubusercontent.com/6513552/147791052-df27ede8-9867-4416-8c1e-ee3c1e054715.png)

2021-12-30 23:21 UTC, euledge commented
検索結果リストにもソーシャルボタン設置しましたが、ここから個別ページに行く誘導 ">>" って用途的には要らなくなりますよね？
どう思われますか？ 
![image](https://user-images.githubusercontent.com/1209580/147793956-1d6f2bf7-fde7-4579-b655-c8de8335e32d.png)

2021-12-31 00:50 UTC, hmatsu47 commented
アコーディオンボタンはてっきりプレビュー環境の都合で消えているのかと思っていました。

ところで、 `clipbordCopy()` として追加されたコードが ES6 のようなので IE では動かない気がするのですが（未確認）、このあたりの機能はもう IE 非対応で良いですよね？

2021-12-31 01:27 UTC, ww2or3ww approved these changes
さっそくありがとうございます！確認しました〜

> ここから個別ページに行く誘導 ">>" って用途的には要らなくなりますよね？

はい、もう不要でOKと思います👍

IEも、まぁ無くていいのでは、と思います(^_^;)

2021-12-31 02:55 UTC, merged